### ISSUE TITLE
OIDC SSO integration in AKS

### ISSUE THREAD

**Issue by sharmavijay86** [OpenUnison/openunison-k8s-idm-oidc#20]
Hey Folks,
This is a query about  SSO OIDC integration with  aks. We ever tested this ? How to make it ( k8s-idm-oidc ) running over there in AKS.

**Comment by mlbiam** [comment]
All of our automation portals (ldap/ad, oidc, saml) are in a state of flux and and being rebuilt around multi-cluster management and updating workflows without a rebuild. If you're interested in trying it out we can get a beta published. We'd love the feedback.

**Comment by sharmavijay86** [comment]
I would love to try and implement in dev environment. Would for sure share you challenges in various environment while testing beta.

**Comment by mlbiam** [comment]
stay tuned.  we'll have something posted by tomorrow

**Comment by mlbiam** [comment]
Here's the docs on how to run the automation portal - https://github.com/mlbiam/openunison-k8s-idm-oidc/blob/master/README.md

Don't use the current helm charts though,  fork https://github.com/mlbiam/helm-charts/tree/dynamicsso and run the charts directly from there.  So instead of `helm install orcehstra tremolo/...` use `helm install orchestra /path/to/helm-charts/...`.  Also, here's my values.yaml as a starting point.  

```
network:
  openunison_host: "k8sou.apps.aks.dev.domain"
  dashboard_host: "k8sdb.apps.aks.dev.domain"
  api_server_host: "k8sapi.apps.aks.dev.domain"
  session_inactivity_timeout_seconds: 900
  k8s_url: https://k8s-installer-master.tremolo.lan:6443
  createIngressCertificate: false
  ingress_type: nginx
  ingress_annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt"
  

cert_template:
  ou: "Kubernetes"
  o: "MyOrg"
  l: "My Cluster"
  st: "State of Cluster"
  c: "MyCountry"

image: "docker.io/tremolosecurity/betas:ouoidc23"
amq_image: "docker.io/tremolosecurity/activemq-docker:latest"
myvd_config_path: "WEB-INF/myvd.conf"
k8s_cluster_name: kubernetes
enable_impersonation: true

dashboard:
  namespace: "kubernetes-dashboard"
  cert_name: "kubernetes-dashboard-certs"
  label: "k8s-app=kubernetes-dashboard"
  service_name: kubernetes-dashboard
certs:
  use_k8s_cm: false

#trusted_certs: []

trusted_certs:
  - name: ldaps
    pem_b64: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURVVENDQWptZ0F3SUJBZ0lFUEcwU0lEQU5CZ2txaGtpRzl3MEJBUXNGQURCWk1Rd3dDZ1lEVlFRR0V3TmsKWlhZeEREQUtCZ05WQkFnVEEyUmxkakVNTUFvR0ExVUVCeE1EWkdWMk1Rd3dDZ1lEVlFRS0V3TmtaWFl4RERBSwpCZ05WQkFzVEEyUmxkakVSTUE4R0ExVUVBeE1JWVhCaFkyaGxaSE13SGhjTk1qRXdOREl4TVRJek9ERTVXaGNOCk16RXdOREU1TVRJek9ERTVXakJaTVF3d0NnWURWUVFHRXdOa1pYWXhEREFLQmdOVkJBZ1RBMlJsZGpFTU1Bb0cKQTFVRUJ4TURaR1YyTVF3d0NnWURWUVFLRXdOa1pYWXhEREFLQmdOVkJBc1RBMlJsZGpFUk1BOEdBMVVFQXhNSQpZWEJoWTJobFpITXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDaTQzVHpCRHd1CkUrQXFWbWRqUjNIaXBNa1pCSVNwNG94bU92Wm5aSlNuWGltU0FvNlRTT1BCc3pKb0RoMzZEb1Z0MDBTQ3RlL0QKcmlmQ01pd0Ryc2paMlRxSXd1K29JU0I3NFFxckVMZnVHQkNWRm1ZbVNwR2dFR1hsbE1wS0xMejIzZHhRMUVuTAp2QThDS3JRUUpHYVNZc1ZZY1JPd1YwaGg3R3dPUXMxQ3hheXQ3R2hobW00Yy9QdDc5a1lIc1hYOHRKNnQxTERGCmFnbVhJVi91WEJmTGJ1aDZsMndsbTQxWVoxQnl0MTRFeEo3bXdaOFhSRmY1ckpmeUVhMVNTUmVndE5qU1VlMTUKaCtUUG8rajRZVG8xdUFidFl6azNlaUl1L3JrVmYyMlVCWGZCaDUvYVY2eHMveXh1SW9KanhQSmFoN0NxaDQ5NwpzUzFXOGRORGN5YlRBZ01CQUFHaklUQWZNQjBHQTFVZERnUVdCQlMxOWJYQjNmcFl6OWNIcUhxSHF1ejN6RnlFCjJUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFhc1FnSExPUHpKM0gxOEJwaEVUcDhXeGx1Z1crVndlaFl1T2IKMVVCaUpsMWVvNHdzZkx1Tm51VUJ4QVZCdUtsMWliZXIwSFZ4aG1kTnNpNndBdE1obmVTcW5kemU2Q0VOWVBMMgpUZk5NdHAyUkk1MEZrZk5ROFlkS2p0OGlKUnhPNUdvdGpGRWtpWVAveElGUWJyQ3RiQmdkUDc1ZWIrUjl5MjBvCjBOUE5OVVNrZFBxRGZ1b1FWTmp1c2tBRE9hM1F1RVFEQ3NTLzJjSkhJY3R4YXJLVUtJY2xCa25YcFZHVEZDbVcKem8rWjRCSEg4aHkrY3VqRG9lTlQ2MFIvMGdLNkRTQlFaaHhwWTlsaE1samRkQTZOdVYrK0JNeTZzRmUzYlFmMQpKTzFpbWE2cGhBeGNLaTVlU0EvSWFJUkU0VHFLdzg3c0EwZ3JuamVFSHdwYnJVM25sdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=

  
oidc:
  client_id: XXXXXX
  auth_url: https://login.microsoftonline.com/YYYYYYYY/oauth2/v2.0/authorize
  token_url: https://login.microsoftonline.com/YYYYYYYY/oauth2/v2.0/token
  user_in_idtoken: true
  userinfo_url: https://graph.microsoft.com/oidc/userinfo
  domain: ""
  scopes: openid email profile
  claims:
    sub: sub
    email: email
    given_name: given_name
    family_name: family_name
    display_name: name
    groups: groups

database:
  hibernate_dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  quartz_dialect: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://mariadb.mariadb.svc:3306/unison
  user: root
  validation: SELECT 1

smtp:
  host: blackhole.blackhole.svc
  port: 1025
  user: "none"
  from: donotreply@domain.com
  tls: false

monitoring:
  prometheus_service_account: system:serviceaccount:monitoring:prometheus-k8s

network_policies:
  enabled: false
  ingress:
    enabled: true
    labels:
      app.kubernetes.io/name: ingress-nginx
  monitoring:
    enabled: true
    labels:
      app.kubernetes.io/name: monitoring
  apiserver:
    enabled: true
    labels:
      app.kubernetes.io/name: kube-system

services:
  enable_tokenrequest: false
  token_request_audience: api
  token_request_expiration_seconds: 600


openunison:
  replicas: 1
  non_secret_data: {}
  secrets: []
```

The docs are a bit of a mess, but we're completely redoing them so bear with us.
